# Generated by Django 2.2.7 on 2020-01-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
