# Generated by Django 2.2.7 on 2020-01-31 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200131_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
