# Generated by Django 2.2.7 on 2020-01-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Brouillon'), (1, 'Publier')], default=0),
        ),
    ]
